Repository es20231/eqp7, pull requests merged in 2023-07, with the labels that each got.

#32 chore: add scripts to run application and eslint
  .github/workflows/next.yml
  package-lock.json
  package.json
  server/.eslintrc.json
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/index.ts
  server/tests/unit/test.spec.ts
  web/.eslintrc.json
  web/package-lock.json
  web/package.json
Labels: chore

#49 feat(web/NextAuth): add next auth to project
  package.json
  web/.env.example
  web/next.config.js
  web/package-lock.json
  web/package.json
  web/src/app/api/auth/[...nextauth]/route.ts
  web/src/app/layout.tsx
  web/src/app/page.tsx
  web/src/middleware.ts
  web/src/providers/app.provider.tsx
Labels: enhancement

#52 feat(server/schema.prisma): creating user model
  server/prisma/data/sqlite.db
  server/prisma/data/sqlite.db-journal
  server/prisma/migrations/20230717192114_create_users_table/migration.sql
  server/prisma/migrations/migration_lock.toml
  server/prisma/schema.prisma
Labels: enhancement

#53 feat(server): add image and user endpoints
  .github/workflows/next.yml
  .github/workflows/server.yml
  .github/workflows/tests.yml
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/prisma/data/sqlite.db
  server/prisma/data/sqlite.db-journal
  server/prisma/migrations/20230714150519_add_image_model/migration.sql
  server/prisma/migrations/20230714190446_mapping_columns_names_and_add_draft_user_model/migration.sql
  server/prisma/migrations/20230714191318_add_datetime_fields_to_models/migration.sql
  server/prisma/migrations/20230716234919_filling_user_fields/migration.sql
  server/prisma/migrations/20230722004926_after_merge_main_feat_server_image_and_user_endpoints/migration.sql
  server/prisma/schema.prisma
  server/src/controllers/image.controller.ts
  server/src/controllers/user.controller.ts
  server/src/dtos/image/create-image.dto.ts
  server/src/dtos/user/create-user.dto.ts
  server/src/dtos/user/update-user.dto.ts
  server/src/entities/image.entity.ts
  server/src/entities/user.entity.ts
  server/src/factories/image.factory.ts
  server/src/factories/user.factory.ts
  server/src/index.ts
  server/src/repositories/iimage.repository.ts
  server/src/repositories/implementations/memory/image.repository.ts
  server/src/repositories/implementations/memory/user.repository.ts
  server/src/repositories/implementations/prisma/image.repository.ts
  server/src/repositories/implementations/prisma/user.repository.ts
  server/src/repositories/iuser.repository.ts
  server/src/routes/image.routes.ts
  server/src/routes/user.routes.ts
  server/src/services/image.service.ts
  server/src/services/result.ts
  server/src/services/user.service.ts
  server/src/utils.ts
  server/tests/integration/repositories/prisma/image.repository.spec.ts
  server/tests/integration/repositories/prisma/user.repository.spec.ts
  server/tests/integration/services/image.service.spec.ts
  server/tests/integration/services/user.service.spec.ts
  server/tests/unit/factories/image.factory.spec.ts
  server/tests/unit/factories/user.factory.spec.ts
  server/tests/unit/repositories/memory/image.repository.spec.ts
  server/tests/unit/repositories/memory/user.repository.spec.ts
  server/tsconfig.json
Labels: enhancement

#57 fix(server/repositories): fix user repository
  .github/workflows/next.yml
  .github/workflows/server.yml
  .gitignore
  package-lock.json
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/repositories/implementations/memory/user.repository.ts
  server/src/repositories/implementations/prisma/user.repository.ts
  server/src/repositories/iuser.repository.ts
  server/tests/integration/repositories/prisma/user.repository.spec.ts
  server/tests/unit/repositories/memory/user.repository.spec.ts
  server/tsconfig.build.json
  server/tsconfig.json
  web/.gitignore
  web/package-lock.json
Labels: bug

#59 fix(server/services): fix user service to return password
  server/src/controllers/user.controller.ts
  server/src/services/user.service.ts
  server/tests/integration/services/user.service.spec.ts
Labels: bug

#60 Feat/server/add auth endpoints
  server/package.json
  server/src/controllers/auth.controller.ts
  server/src/factories/auth.factory.ts
  server/src/index.ts
  server/src/routes/auth.routes.ts
  server/src/services/auth.service.ts
  server/src/services/user.service.ts
Labels: enhancement

#58 feat(server): add post endpoint updated
  server/prisma/database.db
  server/prisma/migrations/20230718003753_create_posts_table/migration.sql
  server/prisma/migrations/20230718203300_remove_subtitle_camel_case/migration.sql
  server/prisma/schema.prisma
  server/src/controllers/post.controller.ts
  server/src/dtos/post/create-post.dto.ts
  server/src/dtos/post/update-post.dto.ts
  server/src/entities/image.entity.ts
  server/src/entities/post.entity.ts
  server/src/entities/user.entity.ts
  server/src/factories/post.factory.ts
  server/src/index.ts
  server/src/lib/prisma.ts
  server/src/repositories/implementations/memory/post.repository.ts
  server/src/repositories/implementations/prisma/post.repository.ts
  server/src/repositories/ipost.repository.ts
  server/src/routes/post.routes.ts
  server/src/services/post.service.ts
  server/tests/integration/repositories/prisma/post.repository.spec.ts
  server/tests/integration/services/post.service.spec.ts
  server/tests/unit/factories/post.factory.spec.ts
  server/tests/unit/repositories/memory/post.repository.spec.ts
  server/tests/unit/test.spec.ts
Labels: enhancement

#56 feat(server): add integration with dropbox api
  server/.env.example
  server/package.json
  server/prisma/database.db
  server/src/controllers/image.controller.ts
  server/src/index.ts
  server/src/lib/dropbox.ts
  server/src/services/upload-image.service.ts
Labels: enhancement

#63 feat(server): add email verification
  package.json
  server/package.json
  server/prisma/migrations/20230723192605_add_activate_token_model/migration.sql
  server/prisma/schema.prisma
  server/src/controllers/auth.controller.ts
  server/src/controllers/user.controller.ts
  server/src/dtos/activate-token/create-activate-token.dto.ts
  server/src/dtos/activate-token/update-activate-token.dto.ts
  server/src/dtos/user/update-user.dto.ts
  server/src/entities/activate-token.entity.ts
  server/src/factories/activate-token.factory.ts
  server/src/factories/auth.factory.ts
  server/src/lib/mailgun.ts
  server/src/lib/nodemailer.ts
  server/src/repositories/iactivate-token.repository.ts
  server/src/repositories/implementations/memory/activate-token.repository.ts
  server/src/repositories/implementations/prisma/activate-token.repository.ts
  server/src/routes/auth.routes.ts
  server/src/services/activate-token.service.ts
  server/src/services/auth.service.ts
  server/src/services/outsourced/IMailService.ts
  server/src/services/outsourced/implementations/MailgunMailService.ts
  server/src/services/outsourced/implementations/NodemailerMailService.ts
  server/src/services/user.service.ts
  server/tests/integration/repositories/prisma/activate-token.repository.spec.ts
  server/tests/integration/services/activate-token.service.spec.ts
  server/tests/integration/services/image.service.spec.ts
  server/tests/integration/services/post.service.spec.ts
  server/tests/unit/factories/activate-token.factory.spec.ts
  server/tests/unit/repositories/memory/activate-token.repository.spec.ts
Labels: enhancement

#62 chore(server): integrate post module
  server/package.json
  server/src/controllers/auth.controller.ts
  server/src/controllers/user.controller.ts
  server/src/entities/post.entity.ts
  server/src/factories/auth.factory.ts
  server/src/factories/user.factory.ts
  server/src/services/auth.service.ts
  server/src/services/user.service.ts
  server/tests/integration/services/user.service.spec.ts
  server/tests/unit/factories/user.factory.spec.ts
Labels: refactor

#66 fix(server/controllers): fix update method
  server/src/controllers/post.controller.ts
Labels: bug

#64 docs: add test plan
  docs/test/plano-de-teste.md
  server/package.json
Labels: documentation

#54 feat(server/middlewares): add auth middleware
  server/package.json
  server/src/middlewares/auth.middleware.ts
  server/src/routes/image.routes.ts
  server/src/routes/post.routes.ts
  server/src/routes/user.routes.ts
Labels: enhancement

#67 feat(web): Implementing interface
  .github/workflows/next.yml
  desktop.ini
  web/package.json
  web/public/dislike.svg
  web/public/heart-dislike.svg
  web/public/heart-like.svg
  web/public/heart.svg
  web/public/logo-min-ig-dark-mode.svg
  web/public/logo-min-ig-light-mode.svg
  web/public/logo-min-ig.svg
  web/public/profile.svg
  web/public/wave-blue.svg
  web/public/wave-green.svg
  web/src/app/auth/login/page.tsx
  web/src/app/auth/register/page.tsx
  web/src/app/posts/page.tsx
  web/src/components/Button.tsx
  web/src/components/Checkbox.tsx
  web/src/components/Form/Parts/ErrorMessage.tsx
  web/src/components/Form/Parts/Field.tsx
  web/src/components/Form/Parts/Input.tsx
  web/src/components/Form/Parts/Label.tsx
  web/src/components/Form/Parts/index.tsx
  web/src/components/Form/Providers/LoginForm.tsx
  web/src/components/Form/Providers/RegisterForm.tsx
  web/src/components/Logo.tsx
  web/src/components/Navbar.tsx
  web/src/components/PasswordStrength.tsx
  web/src/components/PostCard.tsx
  web/src/components/PostModal.tsx
  web/src/components/Waves.tsx
  web/tailwind.config.js
Labels: enhancement

#70 feat(web): add login page
  docs/test/test-results.csv
  package.json
  server/src/controllers/image.controller.ts
  server/src/index.ts
  server/src/routes/user.routes.ts
  web/.env.example
  web/next.config.js
  web/package.json
  web/public/logo-dark.svg
  web/public/logo-light.svg
  web/public/next.svg
  web/public/vercel.svg
  web/public/waves-dark.svg
  web/public/waves-light.svg
  web/src/@types/next-auth.d.ts
  web/src/app/api/auth/[...nextauth]/route.ts
  web/src/app/auth/login/page.tsx
  web/src/app/dashboard/layout.tsx
  web/src/app/dashboard/page.tsx
  web/src/app/favicon.ico
  web/src/app/globals.css
  web/src/app/layout.tsx
  web/src/assets/error-page.json
  web/src/components/Button.tsx
  web/src/components/Error.tsx
  web/src/components/Form/Parts/ErrorMessage.tsx
  web/src/components/Form/Parts/Field.tsx
  web/src/components/Form/Parts/Input.tsx
  web/src/components/Form/Parts/Label.tsx
  web/src/components/Form/Parts/index.tsx
  web/src/components/Form/Providers/LoginForm.tsx
  web/src/components/Logo.tsx
  web/src/components/Text.tsx
  web/src/components/ThemeSwitch.tsx
  web/src/components/Title.tsx
  web/src/components/UserImages.tsx
  web/src/components/Waves.tsx
  web/src/middleware.ts
  web/src/providers/app.provider.tsx
  web/src/queries/user.query.ts
  web/src/services/axios.ts
  web/src/services/queryClient.ts
  web/src/stores/user.store.ts
  web/tailwind.config.js
Labels: enhancement

#100 feat(server): add docs endpoint
  server/package.json
  server/src/controllers/auth.controller.ts
  server/src/controllers/post.controller.ts
  server/src/docs/swagger/schemas/auth.schema.ts
  server/src/docs/swagger/schemas/image.schema.ts
  server/src/docs/swagger/schemas/post.schema.ts
  server/src/docs/swagger/schemas/user.schema.ts
  server/src/index.ts
  server/src/routes/auth.routes.ts
  server/src/routes/image.routes.ts
  server/src/routes/post.routes.ts
  server/src/routes/user.routes.ts
  server/src/services/auth.service.ts
Labels: documentation, enhancement
